# Test Workflow
name: Test CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Hello World! The workflow is triggering."
